### ISSUE TITLE
CI USER STORY: Polls feedback

### ISSUE THREAD

**Issue by tomdu3** [tomdu3/myFirstAgileProject#3]
As a **site user** I can **give feedback to  by checking a prepared list  of possible comments in polls relative to activities ** so that **I could have a reference for the said activity**

# Acceptance Criteria:
- A checkbox list of possible comments is prepared
- user can select the feedback by clicking on the checkbox
- user can insert a different comment defined by them

# Tasks:
- [ ] make a list of possible comments, positive, negative
- [ ] put the check boxes next to the options to choose
- [ ] add possibility for multiple choices
- [ ] add an option - other for user to write it themselves 
- [ ] make a submit button noticeable
- [ ] provide the message of the successful submission
