### ISSUE TITLE
CI USER STORY: Anonymous feedback

### ISSUE THREAD

**Issue by tomdu3** [tomdu3/myFirstAgileProject#4]
In order to **protect my privacy** as a **site user**, I can **give my feedback anonymously**

# Acceptance Criteria:
- There's an Anonymous checkbox/option
- User is asked if they want the feedback be anonymous
-  User can see immediately after submission if their comment was anonymous

# Tasks:
- [ ] make the option for anonymous feedback a default choice
- [ ] make the anonymous option visible
- [ ] put the option next to the submit button
